apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemowebapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mydemowebapp
  template:
    metadata:
      labels:
        app: mydemowebapp
    spec:
      containers:
      - name: hello-world
        image: nathai/mydemowebapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydemowebapp
spec:
  type: NodePort
  selector:
    app: mydemowebapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodeport: 32000